### ISSUE TITLE
Ruby with Dark mode

### ISSUE THREAD

**Issue by NickG13** [TryGhost/Ruby#16]
Hi! 
Just loving your theme, only one thing: Would it be possible to add dark mode to Ruby by default? I mean like in Casper, where it changes automatically. 
I think this would give a better experience for a lot of users
Thank you! 
Nick

**Comment by minimaluminium** [comment]
Hey 👋 . We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!

**Comment by NickG13** [comment]
Sorry but in the forum no one replied to me neither I'm not sure the devs have read my suggestion
See https://forum.ghost.org/t/ruby-with-dark-mode/20070
