### ISSUE TITLE
Next / Previous Post with no Feature Image

### ISSUE THREAD

**Issue by jordijansen** [TryGhost/Ruby#20]
I'm using Ruby V1.0.0 on my Ghost instance. And the next / previous buttons are not correctly displaying when no feature image is uploaded for a post. I think it should not try to display an Image in this case?
![image](https://user-images.githubusercontent.com/2795932/148214779-418bc012-c095-4eab-8cd3-f0f3c1279e99.png)

Also see: [https://www.thestartplayer.com/valeria-card-kingdoms/](https://www.thestartplayer.com/valeria-card-kingdoms/)

**Comment by minimaluminium** [comment]
Hey @jordijansen, thanks for your report! This has just been fixed. Download and install the theme again, and the fix will be applied.

**Comment by jordijansen** [comment]
@minimaluminium sorry to bother but I'm on the starter plan for Ghost so I can't install from zip. Will this get pushed to the Ghost platform so I can install it from the Theme browser?

**Comment by minimaluminium** [comment]
@jordijansen All our [official](https://ghost.org/themes/?category=official) themes can be installed from the platform, and all of them are synced with their own repo. We don't do versioning on our themes for the simplicity except Casper. So even though it says v1.0, it's still up to date :)
