### ISSUE TITLE
Collapsed menu is broken (no background)

### ISSUE THREAD

**Issue by jordijansen** [TryGhost/Ruby#22]
Hi,

I'm using the Ruby theme and the collapsed menu (on mobile for example) is broken. The menu has no background.

It's also broken on the live demo: https://ruby.ghost.io/

![image](https://user-images.githubusercontent.com/2795932/180444348-a87ae996-d6a9-45f6-bff4-3eb526b9e2e5.png)

**Comment by KevinVR** [comment]
I can confirm, the same thing is happening when I try to use this theme on the latest version of Ghost.

**Comment by minimaluminium** [comment]
Thanks everyone for the feedbacks! This is now fixed by adding default background color.

**Comment by jordijansen** [comment]
Thanks for the quick fix!
