### ISSUE TITLE
Formatting of the bookmark card is very buggy in desktop normal and condensed screen sizes

### ISSUE THREAD

**Issue by mlolm** [TryGhost/Ruby#3]
I love this theme and have started working with it in one of my sites. My only complaint is: i like to use the bookmark card to link between pages and articles in my site. I find it (normally) looks nicer than a plain old html link. However with this theme the bookmark card is very buggy. Perhaps someone could create a custom bookmark card in the next release to replace the standard bookmark card? One that fits with the smaller columns without breaking? (smaller fonts, better usage of space, and prevention of errors such as those attached).

Let me know how I can help.
![ScreenHunter 782](https://user-images.githubusercontent.com/33991763/98265191-16e4b500-1f89-11eb-8058-6013386c85a6.png)
![ScreenHunter 784](https://user-images.githubusercontent.com/33991763/98265201-18ae7880-1f89-11eb-9a22-9959d22596d5.png)
![ScreenHunter 783](https://user-images.githubusercontent.com/33991763/98265206-19dfa580-1f89-11eb-9a52-04162c6ac4ea.png)

**Comment by minimaluminium** [comment]
Thanks for the feedback! Just fixed the issues in https://github.com/TryGhost/Ruby/commit/b010f2530cad08471545e4bca85b6d3fe414858c. You can now [download](https://github.com/TryGhost/Ruby/archive/master.zip) the theme and reinstall. Tested the fix with the data of your screenshot.

![Screen Shot 2020-11-09 at 1 56 20 PM](https://user-images.githubusercontent.com/1418797/98505178-962cfe00-2293-11eb-8a18-db25a99b8fce.png)
![Screen Shot 2020-11-09 at 1 56 34 PM](https://user-images.githubusercontent.com/1418797/98505189-9927ee80-2293-11eb-8750-98bdf114e28c.png)

**Comment by mlolm** [comment]
Awesome, thank you so much! Quick question: which files were modified to fix this (as I have a few files changed in the theme so as not to overwrite them. Or is there a way I can see which files changed since the last version in github?

**Comment by minimaluminium** [comment]
You can see the full changelog from the theme repo's commits page [here](https://github.com/TryGhost/Ruby/commits/master). And when you select the latest commit which says "Fix book mark styling", you can see the list of changed files and added/deleted code with color diffing.

For this commit, there are 3 changed files - assets/built/screen.css, assets/built/screen.css.map and assets/css/misc/kg.css

**Comment by mlolm** [comment]
Thanks alo!
