### ISSUE TITLE
Dark Mode with Switcher

### ISSUE THREAD

**Issue by mcnaveen** [TryGhost/Ruby#4]
Requesting for Dark Mode with Switcher.

**Comment by matthanley** [comment]
Hey 👋 We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Many questions can be answered by reviewing our documentation. If you can't find an answer then our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

Thanks!
